name: Test package

on:
  push:         {branches: [master]}
  pull_request: {branches: [master]}



jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
      run: python3 setup.py install

    - name: Install dependencies
      use: actions/setup-python@v1
      run: |
       python -m pip install --upgrade pip setuptools wheel
       pip install -r requirements.txt

