name: codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
      - with:
      - name: codecov-umbrella # optional
      - fail_ci_if_error: true # optional (default = false)
      - verbose: true # optional (default = false)